name: Android Build Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Setup Android SDK
      uses: reactivecircus/android-setup-action@v2
      with:
        components: 'build-tools;28.0.3' # Adjust the version according to your project
        licenses: 'android-sdk-license-5be876d5|android-sdk-license-d56f5183|android-sdk-license-c81a61d9'

    - name: Build with Gradle
      run: ./gradlew assembleDebug
